version: "3.3"

services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    env_file:
      - .env
  kowl:
    image: quay.io/cloudhut/kowl:v1.1.0
    restart: on-failure
    hostname: kowl
    volumes:
    - ./kowl:/etc/kowl/
    ports:
    - "9000:8080"
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml   
